import type { WrittenLessonMeta } from '../data-analytics/lessons'

export type { WrittenLessonMeta }

export const PM_LESSON_META: WrittenLessonMeta[] = [
  {
    id: 'l1',
    moduleId: 'm1',
    title: 'What product management is for',
    kind: 'notes',
    objective: 'Separate product work from delivery theatre: name the decision a PM is paid to make.',
    whyItMatters: 'If you cannot say whose problem you are choosing, you will ship activity instead of a product.',
    concepts: ['problem vs solution', 'outcome vs output', 'what this course does not teach'],
    practicalOutput: 'One sentence: the decision this course trains you to make, and one thing it does not claim.',
    assessment: 'Knowledge check in the lesson; product thinking quiz on l3.',
    prerequisite: 'None',
    estimatedMinutes: 40,
  },
  {
    id: 'l2',
    moduleId: 'm1',
    title: 'Problems, users, and outcomes',
    kind: 'notes',
    objective: 'Rewrite a vague request into user, job, outcome, and constraint using the Harbor Desk case.',
    whyItMatters: 'Teams argue about features when they have not agreed who is struggling and what “better” would look like.',
    concepts: ['user', 'job-to-be-done', 'outcome', 'constraint', 'Harbor Retail vs Northwind'],
    practicalOutput: 'Four rewritten asks, including one you refuse because it is a solution in disguise.',
    assessment: 'Knowledge check; l3 quiz.',
    prerequisite: 'l1',
    estimatedMinutes: 40,
  },
  {
    id: 'l3',
    moduleId: 'm1',
    title: 'Product thinking check',
    kind: 'quiz',
    objective: 'Prove you can tell a problem from a solution and an outcome from an output.',
    whyItMatters: 'Later briefs assume this vocabulary.',
    concepts: ['scenario questions on lessons 1–2'],
    practicalOutput: 'Quiz attempt (all five correct).',
    assessment: '5 MCQs, all required.',
    prerequisite: 'l2',
    estimatedMinutes: 20,
  },
  {
    id: 'l4',
    moduleId: 'm2',
    title: 'Talking to users without leading them',
    kind: 'notes',
    objective: 'Turn a leading question into a past-behaviour question and extract a usable quote from a Harbor Desk interview.',
    whyItMatters: 'If you ask “would you use a shared inbox?”, people are polite. Past behaviour is evidence.',
    concepts: ['past behaviour', 'leading questions', 'quote vs paraphrase', 'who not to interview'],
    practicalOutput: 'Two rewritten questions and one labelled quote from the case notes.',
    assessment: 'Knowledge check; assignment l6.',
    prerequisite: 'l3',
    estimatedMinutes: 45,
  },
  {
    id: 'l5',
    moduleId: 'm2',
    title: 'Evidence, not opinions',
    kind: 'notes',
    objective: 'Sort Harbor Desk notes into observation, inference, and opinion, and say what is still missing.',
    whyItMatters: 'A backlog of opinions is not discovery. You need to know which claims would survive a sceptical engineer.',
    concepts: ['observation', 'inference', 'opinion', 'frequency vs intensity', 'gap in evidence'],
    practicalOutput: 'A three-column sort of five claims and one explicit gap.',
    assessment: 'Knowledge check; assignment l6.',
    prerequisite: 'l4',
    estimatedMinutes: 45,
  },
  {
    id: 'l6',
    moduleId: 'm2',
    title: 'Research note — Harbor Desk interviews',
    kind: 'assignment',
    objective: 'Write a research note from the Harbor Desk case: who you heard, what they do today, and what you still do not know.',
    whyItMatters: 'This is the first work sample: evidence before a recommendation.',
    concepts: ['interview synthesis', 'jobs', 'quotes', 'unknowns'],
    practicalOutput: 'A research note with quotes, jobs, and a gap list.',
    assessment: 'Rubric in the brief. No faculty grading yet.',
    prerequisite: 'l5',
    estimatedMinutes: 180,
  },
  {
    id: 'l7',
    moduleId: 'm3',
    title: 'Problem statements that can be tested',
    kind: 'notes',
    objective: 'Write a problem statement with user, context, pain, and how you would know it was less true next month.',
    whyItMatters: '“Stores need better communication” cannot be tested. A statement with a measurable pain can.',
    concepts: ['problem statement template', 'testable', 'too-broad vs too-narrow'],
    practicalOutput: 'One Harbor Desk problem statement and one rejected rewrite.',
    assessment: 'Knowledge check; l9 quiz.',
    prerequisite: 'l6',
    estimatedMinutes: 45,
  },
  {
    id: 'l8',
    moduleId: 'm3',
    title: 'Jobs, constraints, and non-goals',
    kind: 'notes',
    objective: 'Name the job, the hard constraint, and three non-goals for Harbor Desk.',
    whyItMatters: 'Without non-goals, every adjacent request becomes the product.',
    concepts: ['job story', 'constraint', 'non-goal', 'scope'],
    practicalOutput: 'Job story + constraint + three non-goals.',
    assessment: 'Knowledge check; l9 quiz.',
    prerequisite: 'l7',
    estimatedMinutes: 45,
  },
  {
    id: 'l9',
    moduleId: 'm3',
    title: 'Framing check',
    kind: 'quiz',
    objective: 'Prove you can reject a solution-shaped brief and keep a testable problem.',
    whyItMatters: 'The priority memo assumes you can hold the frame.',
    concepts: ['scenario framing questions'],
    practicalOutput: 'Quiz attempt (all five correct).',
    assessment: '5 MCQs, all required.',
    prerequisite: 'l8',
    estimatedMinutes: 20,
  },
  {
    id: 'l10',
    moduleId: 'm4',
    title: 'Opportunity versus solution',
    kind: 'notes',
    objective: 'Split a Harbor Desk idea into the opportunity (job) and the solution (inbox), and list two other solutions to the same job.',
    whyItMatters: 'If the opportunity is “missed weekend exceptions”, a shared inbox is one bet, not the only one.',
    concepts: ['opportunity', 'solution', 'alternative bets'],
    practicalOutput: 'One opportunity, the Harbor Desk bet, two alternatives.',
    assessment: 'Knowledge check; assignment l12.',
    prerequisite: 'l9',
    estimatedMinutes: 45,
  },
  {
    id: 'l11',
    moduleId: 'm4',
    title: 'Choosing one bet',
    kind: 'notes',
    objective: 'Score three Harbor Desk options against reach, evidence, and engineering cost, then pick one and say what you are not doing.',
    whyItMatters: 'Two engineers and six weeks cannot build an ERP. A PM who will not cut scope is not deciding.',
    concepts: ['reach', 'evidence confidence', 'effort', 'kill criteria'],
    practicalOutput: 'A 3-option score table and a one-sentence bet.',
    assessment: 'Knowledge check; assignment l12.',
    prerequisite: 'l10',
    estimatedMinutes: 45,
  },
  {
    id: 'l12',
    moduleId: 'm4',
    title: 'Priority memo — Harbor Desk',
    kind: 'assignment',
    objective: 'Recommend one Harbor Desk bet under the stated constraint and name what you are not building.',
    whyItMatters: 'This is the second work sample: a decision, not a feature list.',
    concepts: ['prioritisation', 'non-goals', 'constraint'],
    practicalOutput: 'A one-page priority memo.',
    assessment: 'Rubric in the brief. No faculty grading yet.',
    prerequisite: 'l11',
    estimatedMinutes: 180,
  },
  {
    id: 'l13',
    moduleId: 'm5',
    title: 'Writing a specification someone can build',
    kind: 'notes',
    objective: 'Write a thin spec: user, trigger, happy path, one edge case, and an out-of-scope line an engineer could implement without a meeting.',
    whyItMatters: 'A slide titled “shared inbox” is not a spec. Ambiguity becomes whatever engineering invents on Thursday.',
    concepts: ['trigger', 'happy path', 'edge case', 'acceptance check', 'out of scope'],
    practicalOutput: 'A one-screen spec for the chosen Harbor Desk bet.',
    assessment: 'Knowledge check; capstone l14.',
    prerequisite: 'l12',
    estimatedMinutes: 50,
  },
  {
    id: 'l14',
    moduleId: 'm5',
    title: 'Capstone — Harbor Desk product case',
    kind: 'assignment',
    objective: 'Produce an end-to-end product case: evidence, frame, one bet, spec, and what you would check in four weeks.',
    whyItMatters: 'Progress percent is not competence. This case is the work sample.',
    concepts: ['research', 'framing', 'prioritisation', 'specification', 'review check'],
    practicalOutput: 'A product-case memo a hiring manager could read without a walkthrough.',
    assessment: 'Capstone rubric. Not a certificate or placement.',
    prerequisite: 'l13',
    estimatedMinutes: 360,
  },
  {
    id: 'l15',
    moduleId: 'm5',
    title: 'Final check',
    kind: 'quiz',
    objective: 'Check judgement on evidence, framing, scope, and honesty about what this course does not teach.',
    whyItMatters: 'The last quiz should not be trivia about frameworks.',
    concepts: ['scenario questions across the course'],
    practicalOutput: 'Quiz attempt (all five correct).',
    assessment: '5 MCQs, all required.',
    prerequisite: 'l14',
    estimatedMinutes: 25,
  },
]

export const PM_TEACHING_LESSON_IDS = PM_LESSON_META.filter((row) => row.kind === 'notes').map((row) => row.id)

export function getPmLessonMeta(id: string): WrittenLessonMeta | undefined {
  return PM_LESSON_META.find((row) => row.id === id)
}
