#!/usr/bin/env bash
#
# Idempotent repository bootstrap for the Skylent LMS Cloud Agent environment.
# Provisions a local PostgreSQL instance, installs Node dependencies, applies
# Prisma migrations, and seeds the catalog. Safe to run repeatedly.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

PG_VERSION="${PG_VERSION:-16}"
PGBIN="/usr/lib/postgresql/${PG_VERSION}/bin"
PGDATA="${PGDATA:-$HOME/pgdata}"
PGPORT="${PGPORT:-5432}"

# 1. Ensure PostgreSQL is installed (stable system dependency).
if ! [ -x "${PGBIN}/postgres" ]; then
  echo "==> Installing PostgreSQL ${PG_VERSION}"
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
fi
export PATH="${PGBIN}:${PATH}"

# 2. Initialize a user-owned data directory once (trust auth for local dev only).
if [ ! -f "${PGDATA}/PG_VERSION" ]; then
  echo "==> Initializing PostgreSQL data directory at ${PGDATA}"
  initdb -D "${PGDATA}" -U postgres --auth=trust --encoding=UTF8
fi

# 3. Start PostgreSQL if it is not already running.
if ! pg_ctl -D "${PGDATA}" status >/dev/null 2>&1; then
  echo "==> Starting PostgreSQL on port ${PGPORT}"
  pg_ctl -D "${PGDATA}" -l "${HOME}/pg.log" -o "-p ${PGPORT} -k /tmp" -w start
fi

# 4. Ensure the application database exists.
if ! psql -h 127.0.0.1 -p "${PGPORT}" -U postgres -tAc \
  "SELECT 1 FROM pg_database WHERE datname='skylent'" | grep -q 1; then
  echo "==> Creating database 'skylent'"
  createdb -h 127.0.0.1 -p "${PGPORT}" -U postgres skylent
fi

# 5. Create a local .env (git-ignored) with a generated session secret if absent.
if [ ! -f .env ]; then
  echo "==> Creating .env for local development"
  SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  cat > .env <<EOF
# Local development environment (generated by .cursor/install.sh).
# The API server listens on 3000; Vite serves the app and proxies /api -> :3000.
DATABASE_URL=postgresql://postgres@127.0.0.1:${PGPORT}/skylent?schema=public
DIRECT_URL=postgresql://postgres@127.0.0.1:${PGPORT}/skylent?schema=public
SESSION_SECRET=${SECRET}
COOKIE_SECURE=false
FRONTEND_URL=http://127.0.0.1:8443
VITE_DEMO_MODE=true
# Deterministic lesson-grounded assistant (no external key required for dev).
SKYLENT_AI_PROVIDER=lesson-grounded
SKYLENT_AI_ALLOW_GROUNDED=1
EOF
fi

# 6. Install Node dependencies (postinstall runs `prisma generate`).
echo "==> Installing Node dependencies"
pnpm install

# 7. Apply migrations and seed catalog data (seed upserts; safe to re-run in dev).
echo "==> Applying database migrations"
pnpm exec prisma migrate deploy
echo "==> Seeding catalog data"
pnpm exec prisma db seed

echo "==> Install complete"
